build:
  version: "3.0"

cards:
  message: "Welcome to MDFinance cards related local APIs "
  contactDetails:
    name: "Drags Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932